### ISSUE TITLE
과제2 피드백

### ISSUE THREAD

**Issue by pyuseon** [Singan/my-example-project#2]
비즈니스 요구사항을 만족해서 구현해 주셨네요. 

* RateLimiter 설정과 관련해서는 다시 한번 확인이 필요할 것 같습니다. 
  기술적 요구사항의 1초의 500번을 만족하는지는 한번 더 확인 부탁드립니다. 

* 테스트 코드를 추가적으로 작성해 주시면 더 완성도 있는 코드가 될 것 같습니다. 

* QueryDSL도 한번 적용해 보셔도 좋을 것 같습니다. 

이번 과제도 고생 많으셨습니다! 😄

**Comment by Singan** [comment]
감사합니다!
